[versions]
spring-boot = "4.1.0"


[libraries]
spring-boot-dependencies = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "spring-boot" }
spring-cloud-starter-gateway-server-webflux = { module = "org.springframework.cloud:spring-cloud-starter-gateway-server-webflux", version = "5.0.3" }


[plugins]
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
